// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXNBy8nlRGgK4Hx-4geyAUl6xEUq1-eF4',
    appId: '1:1036413462892:web:012073137327c104bdeb49',
    messagingSenderId: '1036413462892',
    projectId: 'servify-260124',
    authDomain: 'servify-260124.firebaseapp.com',
    storageBucket: 'servify-260124.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1-cDCUOaoWOIGzeA4-VITHwCGq_jFaQw',
    appId: '1:1036413462892:android:ab8bc120c73d3b76bdeb49',
    messagingSenderId: '1036413462892',
    projectId: 'servify-260124',
    storageBucket: 'servify-260124.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE20Ewc6VFaG1CRV1F1_vlMuWOYlWI4hQ',
    appId: '1:1036413462892:ios:1ee5237f12f13c33bdeb49',
    messagingSenderId: '1036413462892',
    projectId: 'servify-260124',
    storageBucket: 'servify-260124.firebasestorage.app',
    iosClientId: '1036413462892-b2d00n5ikgn9aspet4anhf75fnsrond3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectServify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE20Ewc6VFaG1CRV1F1_vlMuWOYlWI4hQ',
    appId: '1:1036413462892:ios:1ee5237f12f13c33bdeb49',
    messagingSenderId: '1036413462892',
    projectId: 'servify-260124',
    storageBucket: 'servify-260124.firebasestorage.app',
    iosClientId: '1036413462892-b2d00n5ikgn9aspet4anhf75fnsrond3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectServify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXNBy8nlRGgK4Hx-4geyAUl6xEUq1-eF4',
    appId: '1:1036413462892:web:ec4c471bda27ae01bdeb49',
    messagingSenderId: '1036413462892',
    projectId: 'servify-260124',
    authDomain: 'servify-260124.firebaseapp.com',
    storageBucket: 'servify-260124.firebasestorage.app',
  );
}
