// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbQpvMg781SNQsJxTlr30yhySpZvqUJl0',
    appId: '1:498006993645:web:da538875bf3255de1efae4',
    messagingSenderId: '498006993645',
    projectId: 'servify-app-4b50f',
    authDomain: 'servify-app-4b50f.firebaseapp.com',
    storageBucket: 'servify-app-4b50f.firebasestorage.app',
    measurementId: 'G-TJTKGTVKQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYz4-NeR5h1RQs09unLLNMnv3Xewj0Vp0',
    appId: '1:498006993645:android:ca2bef5f3e82d37f1efae4',
    messagingSenderId: '498006993645',
    projectId: 'servify-app-4b50f',
    storageBucket: 'servify-app-4b50f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemmXlIcpTvJNDg3NGVDQe7Z4uGDaPvkY',
    appId: '1:498006993645:ios:f225675ccaf84ba51efae4',
    messagingSenderId: '498006993645',
    projectId: 'servify-app-4b50f',
    storageBucket: 'servify-app-4b50f.firebasestorage.app',
    iosBundleId: 'com.example.projectServify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemmXlIcpTvJNDg3NGVDQe7Z4uGDaPvkY',
    appId: '1:498006993645:ios:f225675ccaf84ba51efae4',
    messagingSenderId: '498006993645',
    projectId: 'servify-app-4b50f',
    storageBucket: 'servify-app-4b50f.firebasestorage.app',
    iosBundleId: 'com.example.projectServify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbQpvMg781SNQsJxTlr30yhySpZvqUJl0',
    appId: '1:498006993645:web:9fa84a588fdb2a8e1efae4',
    messagingSenderId: '498006993645',
    projectId: 'servify-app-4b50f',
    authDomain: 'servify-app-4b50f.firebaseapp.com',
    storageBucket: 'servify-app-4b50f.firebasestorage.app',
    measurementId: 'G-7FS7MQ9XLK',
  );
}
